const MOVIES = [
  { id:1, title:"Neon Horizon", genre:"Sci-Fi", year:2024, rating:8.4, duration:"2h 12m",
    poster:"https://picsum.photos/seed/neonhorizon/400/600",
    backdrop:"https://picsum.photos/seed/neonhorizon-wide/1200/700",
    desc:"A lone pilot uncovers a conspiracy that threatens the last free colony.",
    featured:true, trending:true },
  { id:2, title:"Shattered Silence", genre:"Thriller", year:2023, rating:7.9, duration:"1h 58m",
    poster:"https://picsum.photos/seed/shatteredsilence/400/600",
    backdrop:"https://picsum.photos/seed/shatteredsilence-wide/1200/700",
    desc:"A detective must confront the killer she let slip away years ago.",
    featured:true, trending:true },
  { id:3, title:"The Last Harvest", genre:"Drama", year:2022, rating:8.1, duration:"2h 05m",
    poster:"https://picsum.photos/seed/lastharvest/400/600",
    backdrop:"https://picsum.photos/seed/lastharvest-wide/1200/700",
    desc:"A farming family fights to save their land during the hardest year of their lives.",
    featured:true, trending:false },
  { id:4, title:"Comic Relief", genre:"Comedy", year:2024, rating:7.2, duration:"1h 44m",
    poster:"https://picsum.photos/seed/comicrelief/400/600",
    backdrop:"https://picsum.photos/seed/comicrelief-wide/1200/700",
    desc:"A washed-up stand-up comedian gets one last shot at redemption on live television.",
    featured:false, trending:true },
  { id:5, title:"Crimson Manor", genre:"Horror", year:2023, rating:7.6, duration:"1h 39m",
    poster:"https://picsum.photos/seed/crimsonmanor/400/600",
    backdrop:"https://picsum.photos/seed/crimsonmanor-wide/1200/700",
    desc:"A family inherits an old manor, unaware of the entity that has waited decades for their arrival.",
    featured:false, trending:true },
  { id:6, title:"Skyward Bound", genre:"Animation", year:2024, rating:8.6, duration:"1h 32m",
    poster:"https://picsum.photos/seed/skywardbound/400/600",
    backdrop:"https://picsum.photos/seed/skywardbound-wide/1200/700",
    desc:"A young inventor builds a flying machine to reach the clouds where her mothers stories say magic lives.",
    featured:true, trending:true },
  { id:7, title:"Iron Verdict", genre:"Action", year:2022, rating:7.8, duration:"2h 18m",
    poster:"https://picsum.photos/seed/ironverdict/400/600",
    backdrop:"https://picsum.photos/seed/ironverdict-wide/1200/700",
    desc:"An ex-soldier turned bodyguard must protect a witness from an army of hired killers in one brutal night.",
    featured:false, trending:true },
  { id:8, title:"Paper Moons", genre:"Drama", year:2021, rating:8.0, duration:"1h 51m",
    poster:"https://picsum.photos/seed/papermoons/400/600",
    backdrop:"https://picsum.photos/seed/papermoons-wide/1200/700",
    desc:"Two estranged sisters take a road trip to scatter their fathers ashes, and rebuild what time broke.",
    featured:false, trending:false },
  { id:9, title:"Zero Gravity Blues", genre:"Sci-Fi", year:2023, rating:7.5, duration:"2h 01m",
    poster:"https://picsum.photos/seed/zerogravity/400/600",
    backdrop:"https://picsum.photos/seed/zerogravity-wide/1200/700",
    desc:"Stranded on a dying space station, a crew must decide who gets the last seat home.",
    featured:false, trending:false },
  { id:10, title:"Laugh Track", genre:"Comedy", year:2022, rating:6.9, duration:"1h 36m",
    poster:"https://picsum.photos/seed/laughtrack/400/600",
    backdrop:"https://picsum.photos/seed/laughtrack-wide/1200/700",
    desc:"A sitcom writer discovers his fictional family is secretly based on a real one.",
    featured:false, trending:false },
  { id:11, title:"The Hollow House", genre:"Horror", year:2024, rating:7.3, duration:"1h 47m",
    poster:"https://picsum.photos/seed/hollowhouse/400/600",
    backdrop:"https://picsum.photos/seed/hollowhouse-wide/1200/700",
    desc:"A paranormal investigator livestreams her final case, and the internet watches her disappear.",
    featured:false, trending:false },
  { id:12, title:"Windward", genre:"Animation", year:2023, rating:8.3, duration:"1h 40m",
    poster:"https://picsum.photos/seed/windward/400/600",
    backdrop:"https://picsum.photos/seed/windward-wide/1200/700",
    desc:"A small boat and a stubborn dog set sail to find an island that only appears once a decade.",
    featured:false, trending:false },
  { id:13, title:"Midnight Protocol", genre:"Thriller", year:2024, rating:8.0, duration:"2h 09m",
    poster:"https://picsum.photos/seed/midnightprotocol/400/600",
    backdrop:"https://picsum.photos/seed/midnightprotocol-wide/1200/700",
    desc:"A hacker uncovers a government program thats been reading citizens dreams for a decade.",
    featured:false, trending:true },
  { id:14, title:"Ashes of Tomorrow", genre:"Action", year:2021, rating:7.4, duration:"2h 22m",
    poster:"https://picsum.photos/seed/ashesoftomorrow/400/600",
    backdrop:"https://picsum.photos/seed/ashesoftomorrow-wide/1200/700",
    desc:"In a world rebuilding after collapse, a courier risks everything to deliver a cure across enemy lines.",
    featured:false, trending:false },
  { id:15, title:"Every Small Thing", genre:"Drama", year:2024, rating:8.5, duration:"1h 58m",
    poster:"https://picsum.photos/seed/everysmallthing/400/600",
    backdrop:"https://picsum.photos/seed/everysmallthing-wide/1200/700",
    desc:"A retired teacher and a runaway teenager form an unlikely bond over one unforgettable summer.",
    featured:false, trending:false },
  { id:16, title:"Static", genre:"Sci-Fi", year:2022, rating:7.1, duration:"1h 49m",
    poster:"https://picsum.photos/seed/staticmovie/400/600",
    backdrop:"https://picsum.photos/seed/staticmovie-wide/1200/700",
    desc:"An AI assistant starts warning its user about events before they happen, and no one believes him.",
    featured:false, trending:false },
  { id:17, title:"Punchline", genre:"Comedy", year:2023, rating:7.0, duration:"1h 41m",
    poster:"https://picsum.photos/seed/punchline/400/600",
    backdrop:"https://picsum.photos/seed/punchline-wide/1200/700",
    desc:"Rival comedy clubs go to war over the same open-mic night, and one nervous newcomer.",
    featured:false, trending:false },
  { id:18, title:"The Quiet Room", genre:"Horror", year:2021, rating:7.8, duration:"1h 35m",
    poster:"https://picsum.photos/seed/quietroom/400/600",
    backdrop:"https://picsum.photos/seed/quietroom-wide/1200/700",
    desc:"Something in the walls of apartment 4B only wakes up when the building goes silent.",
    featured:false, trending:false },
  { id:20, title:"Kabir Singh", genre:"Romance", year:2019, rating:7.0, duration:"2h 53m",
    poster:"https://res.cloudinary.com/dtz0urit6/image/upload/q_auto:best,f_jpg/cloudinary-tools-uploads/we2civkhi0zkilxfyshm",
    backdrop:"https://res.cloudinary.com/dtz0urit6/image/upload/q_auto:best,f_jpg/cloudinary-tools-uploads/we2civkhi0zkilxfyshm",
    desc:"A brilliant but self-destructive surgeon spirals into alcohol and rage after losing the love of his life, and must confront his own demons to find redemption.",
    featured:true, trending:true, category:"Bollywood", youtubeId:"RiANSSgCuJk" }
];

const CATEGORIES = ["All","Action","Drama","Sci-Fi","Comedy","Horror","Animation","Thriller","Romance"];

const CATEGORY_ICONS = { "All":"▦", "Action":"⚡", "Drama":"🎭", "Sci-Fi":"🚀", "Comedy":"😂", "Horror":"👻", "Animation":"🎨", "Thriller":"🔪", "Romance":"❤️" };
